import bcrypt from 'bcryptjs';

export function getVetSeedData(userId: number = 2, offset: number = 0) {
  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];
  const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
  const inTwoDays = new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0];
  const nextWeek = new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0];

  return {
    tutors: [
      {
        id: offset + 1,
        owner_id: userId,
        name: 'Mariana Silveira Ramos',
        cpf: '215.438.990-12',
        phone: '(11) 97123-4567',
        whatsapp: '(11) 97123-4567',
        email: 'mariana.silveira@exemplo.com',
        address: 'Rua Oscar Freire',
        address_number: '1420',
        complement: 'Apto 52',
        neighborhood: 'Cerqueira César',
        city: 'São Paulo',
        state: 'SP',
        postal_code: '01426-001',
        notes: 'Tutor muito atenciosa. Cão com histórico de dermatite alérgica e cadela de agility.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 2,
        owner_id: userId,
        name: 'Carlos Eduardo Prado',
        cpf: '319.824.110-44',
        phone: '(11) 98234-5678',
        whatsapp: '(11) 98234-5678',
        email: 'carlos.prado@exemplo.com',
        address: 'Alameda dos Maracatins',
        address_number: '890',
        complement: null,
        neighborhood: 'Moema',
        city: 'São Paulo',
        state: 'SP',
        postal_code: '04089-012',
        notes: 'Prefere atendimentos domiciliares no final da tarde.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 3,
        owner_id: userId,
        name: 'Fernanda Albuquerque Lima',
        cpf: '112.334.556-78',
        phone: '(11) 99345-6789',
        whatsapp: '(11) 99345-6789',
        email: 'fernanda.lima@exemplo.com',
        address: 'Rua Pamplona',
        address_number: '350',
        complement: null,
        neighborhood: 'Jardim Paulista',
        city: 'São Paulo',
        state: 'SP',
        postal_code: '01405-000',
        notes: 'Tutor dedicada, possui uma cadela Spitz e um coelho Mini Lionhead.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],

    patients: [
      {
        id: offset + 1,
        owner_id: userId,
        tutor_id: offset + 1,
        name: 'Thor',
        species: 'Canina',
        custom_species: null,
        breed: 'Golden Retriever',
        gender: 'Macho',
        birth_date: '2021-06-15',
        approximate_age: '5 anos',
        weight_kg: 34.5,
        coat_color: 'Dourado Claro',
        is_neutered: true,
        microchip: '981098102391201',
        photo_url: null,
        notes: 'Animal dócil. Alérgico a picada de pulgas (DAPE). Acompanhamento dermatológico.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 2,
        owner_id: userId,
        tutor_id: offset + 2,
        name: 'Mel',
        species: 'Felina',
        custom_species: null,
        breed: 'SRD (Frajola)',
        gender: 'Fêmea',
        birth_date: '2023-02-10',
        approximate_age: '3 anos',
        weight_kg: 4.2,
        coat_color: 'Preto e Branco',
        is_neutered: true,
        microchip: '981098102391202',
        photo_url: null,
        notes: 'FIV/FeLV negativos. Vacinação V5 e antirrábica em dia.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 3,
        owner_id: userId,
        tutor_id: offset + 3,
        name: 'Paçoca',
        species: 'Canina',
        custom_species: null,
        breed: 'Spitz Alemão (Lulu da Pomerânia)',
        gender: 'Macho',
        birth_date: '2024-01-20',
        approximate_age: '2 anos',
        weight_kg: 3.1,
        coat_color: 'Laranja',
        is_neutered: false,
        microchip: '981098102391203',
        photo_url: null,
        notes: 'Acompanhamento preventivo e profilaxia dental de rotina.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 4,
        owner_id: userId,
        tutor_id: offset + 3,
        name: 'Pipoca',
        species: 'Lagomorfa',
        custom_species: null,
        breed: 'Mini Lionhead',
        gender: 'Fêmea',
        birth_date: '2024-08-05',
        approximate_age: '1 ano',
        weight_kg: 1.4,
        coat_color: 'Branco e Cinza',
        is_neutered: true,
        microchip: '981098102391204',
        photo_url: null,
        notes: 'Coelho de estimação. Monitorar desgaste dos dentes incisivos e dieta rica em feno.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 5,
        owner_id: userId,
        tutor_id: offset + 1,
        name: 'Luna',
        species: 'Canina',
        custom_species: null,
        breed: 'Border Collie',
        gender: 'Fêmea',
        birth_date: '2022-04-12',
        approximate_age: '4 anos',
        weight_kg: 18.2,
        coat_color: 'Preto e Branco',
        is_neutered: true,
        microchip: '981098102391205',
        photo_url: null,
        notes: 'Atleta de agility. Check-up ortopédico e preventivo regular.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 6,
        owner_id: userId,
        tutor_id: offset + 2,
        name: 'Simba',
        species: 'Felina',
        custom_species: null,
        breed: 'Persa',
        gender: 'Macho',
        birth_date: '2020-09-18',
        approximate_age: '6 anos',
        weight_kg: 4.8,
        coat_color: 'Creme',
        is_neutered: true,
        microchip: '981098102391206',
        photo_url: null,
        notes: 'Exames renais preventivos regulares, escovação e controle de bolas de pelo.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],

    appointments: [
      {
        id: offset + 1,
        owner_id: userId,
        tutor_id: offset + 1,
        patient_id: offset + 1,
        date_time: `${todayStr}T09:30:00`,
        duration_minutes: 60,
        address: 'Rua Oscar Freire, 1420 - Apto 52',
        appointment_type: 'Domiciliar / Volante',
        status: 'CONFIRMADO',
        reason: 'Consulta dermatológica e coleta de raspado de pele',
        notes: 'Levar kit de coleta citológica e lâminas.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 2,
        owner_id: userId,
        tutor_id: offset + 2,
        patient_id: offset + 2,
        date_time: `${todayStr}T14:00:00`,
        duration_minutes: 45,
        address: 'Alameda dos Maracatins, 890',
        appointment_type: 'Domiciliar / Volante',
        status: 'CONFIRMADO',
        reason: 'Aplicação de reforço anual de vacina V5 e antirrábica',
        notes: 'Manter caixa de transporte protegida com feromônio facial.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 3,
        owner_id: userId,
        tutor_id: offset + 3,
        patient_id: offset + 3,
        date_time: `${tomorrow}T10:00:00`,
        duration_minutes: 60,
        address: 'Rua Pamplona, 350',
        appointment_type: 'Domiciliar / Volante',
        status: 'AGENDADO',
        reason: 'Avaliação de claudicação e profilaxia dental',
        notes: 'Verificar cálculo dentário em molares superiores.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 4,
        owner_id: userId,
        tutor_id: offset + 3,
        patient_id: offset + 4,
        date_time: `${inTwoDays}T15:30:00`,
        duration_minutes: 45,
        address: 'Rua Pamplona, 350',
        appointment_type: 'Domiciliar / Volante',
        status: 'AGENDADO',
        reason: 'Revisão odontológica em coelho e ajuste nutricional',
        notes: 'Examinar incisivos com otoscópio.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 5,
        owner_id: userId,
        tutor_id: offset + 1,
        patient_id: offset + 5,
        date_time: `${nextWeek}T11:00:00`,
        duration_minutes: 60,
        address: 'Rua Oscar Freire, 1420',
        appointment_type: 'Domiciliar / Volante',
        status: 'AGENDADO',
        reason: 'Avaliação preventiva de ligamentos e condicionamento físico',
        notes: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],

    consultations: [
      {
        id: offset + 1,
        owner_id: userId,
        patient_id: offset + 1,
        patient_name: 'Thor',
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        appointment_id: offset + 1,
        date_time: `${todayStr}T09:30:00`,
        chief_complaint: 'Prurido intenso em patas e flancos com lesões eritematosas após passeio no parque.',
        anamnesis: 'Tutor relata que animal iniciou lambedura compulsiva das patas há 3 dias. Histórico prévio de dermatite alérgica sazonal. Alimentação Super Premium sem alterações recentes.',
        vital_signs: {
          temperature_c: 38.6,
          heart_rate_bpm: 92,
          respiratory_rate_mpm: 24,
          capillary_refill_time_sec: 2,
          blood_pressure: '125/80',
          body_condition_score: 6,
          hydration_status: 'Normal (Adequada)',
          mucous_membranes: 'Normocoradas'
        },
        physical_examination: 'Eritema interdigital em membros anteriores e pélvicos, com presença de colaretes epidérmicos e alopecia perilesional. Ausculta cardiopulmonar sem sopros ou ruídos adventícios. Linfonodos poplíteos normais.',
        diagnosis_suspicions: 'Dermatite atópica canina com piodermite secundária superficial e foliculite bacteriana.',
        prognosis: 'Bom a Favorável com controle terapêutico e manejo ambiental.',
        conduct_plan: 'Instituído tratamento oral com Oclacitinib (Apoquel) para alívio imediato do prurido, associado a banhos terapêuticos semanais com shampoo de Clorexidina a 3%. Coletado raspado cutâneo.',
        prescriptions: [
          {
            id: 'rx-1',
            medication_name: 'Apoquel 16mg (Oclacitinib)',
            active_ingredient: 'Maleato de Oclacitinib',
            dose: '1 comprimido e meio (24mg)',
            frequency: 'A cada 12 horas por 14 dias, após a cada 24 horas',
            duration_days: 14,
            route: 'Oral',
            instructions: 'Administrar junto com um pequeno pedaço de alimento ou petisco para alívio do prurido cutâneo.'
          },
          {
            id: 'rx-2',
            medication_name: 'Shampoo Clorexidina 3% com Miconazol',
            active_ingredient: 'Digluconato de Clorexidina 3% + Miconazol 2%',
            dose: 'Quantidade suficiente para cobrir o corpo',
            frequency: '2 vezes por semana',
            duration_days: 21,
            route: 'Tópica',
            instructions: 'Massagear suavemente nas áreas afetadas e deixar agir por 10 a 15 minutos antes do enxágue completo com água morna.'
          }
        ],
        requested_exams: 'Raspado Cutâneo Profundo / Fita Adesiva Citológica e Hemograma com Contagem de Eosinófilos.',
        requested_exams_justification: 'Pesquisa microscópica de ácaros (Demodex / Sarcoptes) e citologia para quantificação bacteriana e leveduriforme (Malassezia).',
        billing_items: [
          {
            id: 'bill-1',
            category: 'CONSULTA',
            description: 'Consulta Clínica Volante Domiciliar',
            quantity: 1,
            unit_price: 180,
            total_price: 180
          },
          {
            id: 'bill-2',
            category: 'EXAME',
            description: 'Raspado Cutâneo / Citologia Dermatológica',
            quantity: 1,
            unit_price: 60,
            total_price: 60
          }
        ],
        notes: 'Agendado retorno domiciliar em 15 dias para reavaliação da melhora do prurido e cicatrização das lesões.'
      },
      {
        id: offset + 2,
        owner_id: userId,
        patient_id: offset + 2,
        patient_name: 'Mel',
        tutor_id: offset + 2,
        tutor_name: 'Carlos Eduardo Prado',
        appointment_id: offset + 2,
        date_time: `${todayStr}T14:00:00`,
        chief_complaint: 'Consulta de rotina anual para reforço de vacina V5 e antirrábica.',
        anamnesis: 'Gata vive exclusivamente em apartamento telado. Sem acesso à rua. Alimentação úmida e seca. Nega êmese, tosse ou alterações intestinais.',
        vital_signs: {
          temperature_c: 38.2,
          heart_rate_bpm: 160,
          respiratory_rate_mpm: 30,
          capillary_refill_time_sec: 2,
          body_condition_score: 5,
          hydration_status: 'Normal (Adequada)',
          mucous_membranes: 'Normocoradas'
        },
        physical_examination: 'Paciente calma, bom escore corporal. Pelagem brilhante, dentes sem acúmulo severo de tártaro. Ausculta cardíaca rítmica normofonética sem sopros. Palpação abdominal indolor.',
        diagnosis_suspicions: 'Paciente hígida, apta para imunização profilática.',
        prognosis: 'Excelente.',
        conduct_plan: 'Aplicada 1 dose de vacina quíntupla felina (V5 Felocell) e 1 dose de vacina antirrábica (Nobivac Raiva) por via subcutânea em membros posteriores alternados.',
        prescriptions: [],
        vaccines: [
          {
            id: 'vac-mel-1',
            vaccine_name: 'Vacina Quíntupla Felina (V5)',
            manufacturer: 'Zoetis',
            batch_number: 'ZT-59201',
            application_date: todayStr,
            next_booster_date: new Date(Date.now() + 365 * 86400000).toISOString().split('T')[0],
            route: 'Subcutânea',
            applied_by: 'Dra. Carolina Mendes (CRMV-SP 34892)'
          },
          {
            id: 'vac-mel-2',
            vaccine_name: 'Vacina Antirrábica Felina',
            manufacturer: 'MSD Saúde Animal',
            batch_number: 'MS-88120',
            application_date: todayStr,
            next_booster_date: new Date(Date.now() + 365 * 86400000).toISOString().split('T')[0],
            route: 'Subcutânea',
            applied_by: 'Dra. Carolina Mendes (CRMV-SP 34892)'
          }
        ],
        requested_exams: '',
        billing_items: [
          {
            id: 'bill-3',
            category: 'CONSULTA',
            description: 'Consulta Clínica Volante Domiciliar',
            quantity: 1,
            unit_price: 180,
            total_price: 180
          },
          {
            id: 'bill-4',
            category: 'VACINA',
            description: 'Vacina V4 / V5 Felina (Dose + Aplicação)',
            quantity: 1,
            unit_price: 120,
            total_price: 120
          },
          {
            id: 'bill-5',
            category: 'VACINA',
            description: 'Vacina Antirrábica (Dose + Aplicação)',
            quantity: 1,
            unit_price: 80,
            total_price: 80
          }
        ],
        notes: 'Emitida carteirinha digital de vacinação com QR Code. Próximo reforço em 1 ano.'
      },
      {
        id: offset + 3,
        owner_id: userId,
        patient_id: offset + 3,
        patient_name: 'Paçoca',
        tutor_id: offset + 3,
        tutor_name: 'Fernanda Albuquerque Lima',
        date_time: `${todayStr}T11:00:00`,
        chief_complaint: 'Mau hálito e acúmulo visível de placa bacteriana nos dentes pré-molares.',
        anamnesis: 'Tutor relata halitose leve a moderada há cerca de 2 meses. Cão ativo, boa ingestão hídrica e alimentar. Nunca realizou tartarectomia prévia.',
        vital_signs: {
          temperature_c: 38.5,
          heart_rate_bpm: 110,
          respiratory_rate_mpm: 26,
          capillary_refill_time_sec: 1,
          body_condition_score: 5,
          hydration_status: 'Normal (Adequada)',
          mucous_membranes: 'Normocoradas'
        },
        physical_examination: 'Presença de cálculo dentário grau I a II em pré-molares superiores bilaterais, com gengivite marginal discreta. Sem mobilidade dentária evidente. Demais sistemas sem alterações.',
        diagnosis_suspicions: 'Doença periodontal canina estágio I (gengivite e deposição de cálculo tártaro).',
        prognosis: 'Muito favorável.',
        conduct_plan: 'Indicada higienização oral diária com gel enzimático veterinário e recomendada profilaxia odontológica ultrassônica se houver progressão.',
        prescriptions: [
          {
            id: 'rx-3',
            medication_name: 'Gel Dental Enzimático Veterinário (Orozyme)',
            active_ingredient: 'Complexo Enzimático Amilase + Glicose Oxidase',
            dose: '1 ponta de dedo ou dedeira de silicone',
            frequency: '1 vez ao dia após a última refeição',
            duration_days: 60,
            route: 'Tópica',
            instructions: 'Aplicar diretamente sobre as gengivas e dentes laterais sem necessidade de enxágue posterior.'
          }
        ],
        requested_exams: '',
        billing_items: [
          {
            id: 'bill-6',
            category: 'CONSULTA',
            description: 'Consulta Clínica Volante Domiciliar',
            quantity: 1,
            unit_price: 180,
            total_price: 180
          }
        ],
        notes: 'Orientado tutor quanto ao uso de brinquedos mastigáveis específicos para redução de placa.'
      },
      {
        id: offset + 4,
        owner_id: userId,
        patient_id: offset + 4,
        patient_name: 'Pipoca',
        tutor_id: offset + 3,
        tutor_name: 'Fernanda Albuquerque Lima',
        date_time: `${todayStr}T16:00:00`,
        chief_complaint: 'Avaliação clínica de rotina e orientação nutricional para coelho jovem.',
        anamnesis: 'Animal resgatado com 6 meses de idade, atualmente com 1 ano. Alimentação à base de ração extrusada, necessitando ampliar consumo de feno de gramíneas.',
        vital_signs: {
          temperature_c: 39.1,
          heart_rate_bpm: 220,
          respiratory_rate_mpm: 55,
          capillary_refill_time_sec: 1,
          body_condition_score: 5,
          hydration_status: 'Normal (Adequada)',
          mucous_membranes: 'Normocoradas'
        },
        physical_examination: 'Boa conformação corporal, oclusão dos dentes incisivos perfeita sem sinais de má oclusão ou pontas dentárias. Ausculta cecal ativa com borborigmos fisiológicos normais. Glândulas perianais limpas.',
        diagnosis_suspicions: 'Coelho saudável (hígido), bom desenvolvimento ponderal.',
        prognosis: 'Excelente.',
        conduct_plan: 'Ajuste da dieta para 80% feno timothy/tifton à vontade, 15% folhas verdes escuras higienizadas e 5% ração extrusada de alta fibra.',
        prescriptions: [],
        requested_exams: '',
        billing_items: [
          {
            id: 'bill-7',
            category: 'CONSULTA',
            description: 'Consulta Clínica Volante Domiciliar',
            quantity: 1,
            unit_price: 180,
            total_price: 180
          }
        ],
        notes: 'Entregue manual de cuidados e nutrição de lagomorfos da Dra. Carolina Mendes.'
      }
    ],

    inventory_items: [
      {
        id: offset + 1,
        owner_id: userId,
        item_type: 'MEDICAMENTO',
        name: 'Zoletil 50 (Tiletamina + Zolazepam)',
        active_ingredient: 'Cloridrato de Tiletamina + Zolazepam',
        category: 'Medicamento',
        presentation: 'Frasco ampola liofilizado + diluente 5ml',
        concentration: '50mg/ml',
        presentation_type: 'LIQUIDO_ML',
        unit: 'frasco',
        stock_quantity: 6,
        quantity_in_stock: 4,
        quantity_in_kit: 2,
        min_stock: 2,
        cost_price: 120,
        sale_price: 190,
        batch_number: 'ZL-98421',
        expiry_date: '2027-11-30',
        supplier_name: 'Distribuidora VetBrasil',
        notes: 'Anestésico dissociativo injetável para cães e gatos.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 2,
        owner_id: userId,
        item_type: 'MEDICAMENTO',
        name: 'Meloxicam Injetável 0.2%',
        active_ingredient: 'Meloxicam',
        category: 'Medicamento',
        presentation: 'Frasco ampola 20ml',
        concentration: '2mg/ml',
        presentation_type: 'LIQUIDO_ML',
        unit: 'frasco',
        stock_quantity: 8,
        quantity_in_stock: 5,
        quantity_in_kit: 3,
        min_stock: 3,
        cost_price: 45,
        sale_price: 80,
        batch_number: 'MX-44210',
        expiry_date: '2027-08-15',
        supplier_name: 'BioVet Distribuição',
        notes: 'Anti-inflamatório não esteroidal de eleição.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 3,
        owner_id: userId,
        item_type: 'MEDICAMENTO',
        name: 'Dipirona Gotas 500mg/mL',
        active_ingredient: 'Dipirona Sódica',
        category: 'Medicamento',
        presentation: 'Frasco conta-gotas 20ml',
        concentration: '500mg/ml',
        presentation_type: 'LIQUIDO_ML',
        unit: 'frasco',
        stock_quantity: 12,
        quantity_in_stock: 8,
        quantity_in_kit: 4,
        min_stock: 4,
        cost_price: 18,
        sale_price: 38,
        batch_number: 'DP-2026',
        expiry_date: '2028-02-28',
        supplier_name: 'VetFarma',
        notes: 'Uso oral comum em analgesia e antitérmico.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 4,
        owner_id: userId,
        item_type: 'VACINA',
        name: 'Vacina Vanguard Plus V10',
        active_ingredient: 'Antígenos atenuados caninos múltiplos',
        category: 'Vacina',
        presentation: 'Dose individual liofilizada + diluente 1ml',
        concentration: '1 dose',
        presentation_type: 'LIQUIDO_ML',
        unit: 'dose',
        stock_quantity: 15,
        quantity_in_stock: 9,
        quantity_in_kit: 6,
        min_stock: 5,
        cost_price: 35,
        sale_price: 110,
        batch_number: 'VG-7782',
        expiry_date: '2027-06-30',
        supplier_name: 'Distribuidora VetBrasil',
        notes: 'Manter na maleta térmica refrigerada entre 2°C e 8°C.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 5,
        owner_id: userId,
        item_type: 'VACINA',
        name: 'Vacina Felocell V5 (Quíntupla Felina)',
        active_ingredient: 'Vírus atenuados múltiplos + Chlamydia + FeLV',
        category: 'Vacina',
        presentation: 'Dose individual liofilizada + diluente 1ml',
        concentration: '1 dose',
        presentation_type: 'LIQUIDO_ML',
        unit: 'dose',
        stock_quantity: 10,
        quantity_in_stock: 6,
        quantity_in_kit: 4,
        min_stock: 4,
        cost_price: 45,
        sale_price: 120,
        batch_number: 'FC-9912',
        expiry_date: '2027-09-15',
        supplier_name: 'Zoetis Brasil',
        notes: 'Uso exclusivo em gatos com teste FIV/FeLV negativo.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 6,
        owner_id: userId,
        item_type: 'MEDICAMENTO',
        name: 'Cefalexina 500mg Comprimidos',
        active_ingredient: 'Cefalexina Monohidratada',
        category: 'Medicamento',
        presentation: 'Caixa com 10 comprimidos palatáveis',
        concentration: '500mg',
        presentation_type: 'COMPRIMIDO',
        unit: 'comprimido',
        stock_quantity: 30,
        quantity_in_stock: 20,
        quantity_in_kit: 10,
        min_stock: 10,
        cost_price: 4.5,
        sale_price: 9.0,
        batch_number: 'CF-1029',
        expiry_date: '2027-12-31',
        supplier_name: 'Distribuidora VetBrasil',
        notes: 'Antibiótico cefalosporínico de 1ª geração para piodermites.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 7,
        owner_id: userId,
        item_type: 'MEDICAMENTO',
        name: 'Tramadol Injetável 50mg/mL',
        active_ingredient: 'Cloridrato de Tramadol',
        category: 'Medicamento',
        presentation: 'Ampola 2ml',
        concentration: '50mg/ml',
        presentation_type: 'LIQUIDO_ML',
        unit: 'ampola',
        stock_quantity: 12,
        quantity_in_stock: 8,
        quantity_in_kit: 4,
        min_stock: 3,
        cost_price: 12,
        sale_price: 35,
        batch_number: 'TR-3391',
        expiry_date: '2027-05-30',
        supplier_name: 'BioVet Distribuição',
        notes: 'Opioide de ação moderada para analgesia cirúrgica e ambulatorial.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 8,
        owner_id: userId,
        item_type: 'MATERIAL',
        name: 'Solução Fisiológica NaCl 0.9% 500mL',
        active_ingredient: 'Cloreto de Sódio 0.9%',
        category: 'Insumo',
        presentation: 'Bolsa flexível 500ml',
        concentration: '0.9%',
        presentation_type: 'LIQUIDO_ML',
        unit: 'bolsa',
        stock_quantity: 14,
        quantity_in_stock: 10,
        quantity_in_kit: 4,
        min_stock: 5,
        cost_price: 8.5,
        sale_price: 25.0,
        batch_number: 'SF-5002',
        expiry_date: '2028-06-30',
        supplier_name: 'Distribuidora VetBrasil',
        notes: 'Fluidoterapia de manutenção e reposição.',
        is_active: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],

    financial_entries: [
      {
        id: offset + 1,
        owner_id: userId,
        entry_type: 'RECEITA',
        category: 'Consulta',
        description: 'Atendimento Domiciliar Dermatológico + Coleta Citológica - Thor',
        amount: 240,
        payment_method: 'PIX',
        status: 'PAGO',
        date: todayStr,
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        patient_id: offset + 1,
        patient_name: 'Thor',
        receipt_number: `REC-${today.getFullYear()}-101`,
        notes: 'Pago via chave PIX CNPJ no ato da consulta.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 2,
        owner_id: userId,
        entry_type: 'RECEITA',
        category: 'Vacina',
        description: 'Consulta Volante + Vacina V5 + Antirrábica - Mel',
        amount: 380,
        payment_method: 'PIX',
        status: 'PAGO',
        date: todayStr,
        tutor_id: offset + 2,
        tutor_name: 'Carlos Eduardo Prado',
        patient_id: offset + 2,
        patient_name: 'Mel',
        receipt_number: `REC-${today.getFullYear()}-102`,
        notes: 'Pago via PIX QR Code.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 3,
        owner_id: userId,
        entry_type: 'RECEITA',
        category: 'Procedimento',
        description: 'Procedimento Anestésico Volante - Thor (Hosp. Jardins / Dr. Roberto)',
        amount: 550,
        payment_method: 'PIX',
        status: 'PAGO',
        date: todayStr,
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        patient_id: offset + 1,
        patient_name: 'Thor',
        clinic_name: 'Hospital Veterinário Jardins 24h',
        receipt_number: `REC-${today.getFullYear()}-103`,
        notes: 'Honorário anestésico recebido.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 4,
        owner_id: userId,
        entry_type: 'RECEITA',
        category: 'Consulta',
        description: 'Consulta Domiciliar e Profilaxia Oral - Paçoca',
        amount: 180,
        payment_method: 'CARTAO_CREDITO',
        status: 'PAGO',
        date: todayStr,
        tutor_id: offset + 3,
        tutor_name: 'Fernanda Albuquerque Lima',
        patient_id: offset + 3,
        patient_name: 'Paçoca',
        receipt_number: `REC-${today.getFullYear()}-104`,
        notes: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 5,
        owner_id: userId,
        entry_type: 'DESPESA',
        category: 'Insumos & Medicamentos',
        description: 'Reposição de Maleta Volante: Vacinas V10 e Agulhas Descartáveis',
        amount: 280,
        payment_method: 'PIX',
        status: 'PAGO',
        date: todayStr,
        receipt_number: 'NF-89210',
        notes: 'Distribuidora VetBrasil.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: offset + 6,
        owner_id: userId,
        entry_type: 'RECEITA',
        category: 'Consulta',
        description: 'Avaliação Nutricional e Exame Físico em Coelho - Pipoca',
        amount: 180,
        payment_method: 'PIX',
        status: 'PENDENTE',
        date: tomorrow,
        due_date: tomorrow,
        tutor_id: offset + 3,
        tutor_name: 'Fernanda Albuquerque Lima',
        patient_id: offset + 4,
        patient_name: 'Pipoca',
        receipt_number: `REC-${today.getFullYear()}-105`,
        notes: 'Agendamento confirmado para amanhã.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }
    ],

    clinics: [
      {
        id: offset + 1,
        owner_id: userId,
        code: 'CL-01',
        name: 'Hospital Veterinário Jardins 24h',
        corporate_name: 'Hospital Veterinário Jardins e Diagnóstico Avançado Ltda',
        cnpj: '12.345.678/0001-90',
        phone: '(11) 3088-1234',
        whatsapp: '(11) 98111-2233',
        email: 'contato@hospvetjardins.com.br',
        address: 'Rua Bela Cintra',
        address_number: '2100',
        neighborhood: 'Consolação',
        city: 'São Paulo',
        state: 'SP',
        postal_code: '01415-002',
        manager_name: 'Dr. Roberto Sanches',
        financial_contact: 'Financeiro Jardins - financeiro@hospvetjardins.com.br',
        payment_terms: 'Faturamento quinzenal com repasse via PIX.',
        billing_type: 'FATURAMENTO_PERIODICO',
        billing_closing_day: 15,
        billing_due_day: 20,
        price_table_type: 'PADRAO',
        notes: 'Centro cirúrgico de ponta com monitor multiparamétrico, capnografia e UTI móvel.',
        is_active: true,
        created_at: new Date().toISOString(),
        total_procedures: 14,
        total_billed: 8900.0
      },
      {
        id: offset + 2,
        owner_id: userId,
        code: 'CL-02',
        name: 'Clínica Veterinária PetSoul Moema',
        corporate_name: 'PetSoul Clínica de Especialidades Veterinárias Eireli',
        cnpj: '28.987.654/0001-33',
        phone: '(11) 5051-4321',
        whatsapp: '(11) 97222-3344',
        email: 'cirurgia@petsoulmoema.com.br',
        address: 'Avenida Pavão',
        address_number: '430',
        neighborhood: 'Moema',
        city: 'São Paulo',
        state: 'SP',
        postal_code: '04516-011',
        manager_name: 'Dra. Camila Toledo',
        financial_contact: 'Mariana - financeiro@petsoul.com.br',
        payment_terms: 'Faturamento direto ao tutor no ato do procedimento.',
        billing_type: 'DIRETO_TUTOR',
        billing_closing_day: 30,
        billing_due_day: 5,
        price_table_type: 'PARCEIRO_DIFERENCIADO',
        notes: 'Excelente estrutura para cirurgias de tecidos moles e oncologia.',
        is_active: true,
        created_at: new Date().toISOString(),
        total_procedures: 8,
        total_billed: 5200.0
      },
      {
        id: offset + 3,
        owner_id: userId,
        code: 'CL-03',
        name: 'Centro Cirúrgico VetCare Vila Mariana',
        corporate_name: 'VetCare Centro Especializado em Cirurgia Animal Ltda',
        cnpj: '45.123.890/0001-77',
        phone: '(11) 5572-9090',
        whatsapp: '(11) 97654-1122',
        email: 'adm@vetcarevm.com.br',
        address: 'Rua Domingos de Morais',
        address_number: '1850',
        neighborhood: 'Vila Mariana',
        city: 'São Paulo',
        state: 'SP',
        postal_code: '04010-200',
        manager_name: 'Dra. Beatriz Fontana',
        financial_contact: 'Carlos Contabilidade - financeiro@vetcarevm.com.br',
        payment_terms: 'Faturamento quinzenal (dias 15 e 30).',
        billing_type: 'FATURAMENTO_PERIODICO',
        billing_closing_day: 30,
        billing_due_day: 10,
        price_table_type: 'PADRAO',
        notes: 'Especialistas em ortopedia e neurocirurgia.',
        is_active: true,
        created_at: new Date().toISOString(),
        total_procedures: 6,
        total_billed: 4100.0
      }
    ],

    surgeons: [
      {
        id: offset + 1,
        owner_id: userId,
        code: 'PR-01',
        name: 'Dr. Roberto Sanches',
        crmv: '18450',
        crmv_uf: 'SP',
        specialty: 'Cirurgia Geral & Oncologia',
        phone: '(11) 98111-2233',
        email: 'roberto.sanches@hospvetjardins.com.br',
        primary_clinic_id: offset + 1,
        primary_clinic_name: 'Hospital Veterinário Jardins 24h',
        notes: 'Membro titular do Colégio Brasileiro de Cirurgia Veterinária.',
        is_active: true,
        created_at: new Date().toISOString(),
        total_surgeries: 12
      },
      {
        id: offset + 2,
        owner_id: userId,
        code: 'PR-02',
        name: 'Dra. Camila Toledo',
        crmv: '24190',
        crmv_uf: 'SP',
        specialty: 'Cirurgia de Tecidos Moles & Reconstrutiva',
        phone: '(11) 97222-3344',
        email: 'camila.toledo@petsoulmoema.com.br',
        primary_clinic_id: offset + 2,
        primary_clinic_name: 'Clínica Veterinária PetSoul Moema',
        notes: 'Pós-graduada em cirurgias torácicas e abdominais.',
        is_active: true,
        created_at: new Date().toISOString(),
        total_surgeries: 8
      },
      {
        id: offset + 3,
        owner_id: userId,
        code: 'PR-03',
        name: 'Dra. Beatriz Fontana',
        crmv: '29812',
        crmv_uf: 'SP',
        specialty: 'Ortopedia & Neurocirurgia',
        phone: '(11) 97654-1122',
        email: 'beatriz.fontana@vetcarevm.com.br',
        primary_clinic_id: offset + 3,
        primary_clinic_name: 'Centro Cirúrgico VetCare Vila Mariana',
        notes: 'Especialista em fraturas complexas e coluna vertebral.',
        is_active: true,
        created_at: new Date().toISOString(),
        total_surgeries: 6
      }
    ],

    anesthesia_records: [
      {
        id: offset + 1,
        owner_id: userId,
        code: 'AN-2026-001',
        patient_id: offset + 1,
        patient_name: 'Thor',
        patient_species: 'Canina',
        patient_breed: 'Golden Retriever',
        patient_age: '5 anos',
        patient_weight_kg: 34.5,
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        clinic_id: offset + 1,
        clinic_name: 'Hospital Veterinário Jardins 24h',
        surgeon_id: offset + 1,
        surgeon_name: 'Dr. Roberto Sanches',
        procedure_name: 'Exérese de nódulo cutâneo com margem cirúrgica ampla (Mastocitoma)',
        status: 'FINALIZADA',
        asa_classification: 'ASA II',
        procedure_type: 'ELETIVA',
        date_time: `${todayStr}T08:00:00`,
        pre_anesthetic_evaluation: {
          fasting_water_hours: 2,
          fasting_food_hours: 8,
          general_condition: 'Ativo e cooperativo, mucosa normocorada.',
          heart_rate_bpm: 96,
          respiratory_rate_mpm: 22,
          blood_pressure: '125/85',
          body_temperature_c: 38.4,
          hydration_status: 'Normal (Adequada)'
        },
        procedure_times: {
          mpa_time: '08:15',
          induction_time: '08:35',
          anesthesia_start_time: '08:40',
          procedure_start_time: '08:50',
          procedure_end_time: '09:45',
          anesthesia_end_time: '09:50',
          extubation_time: '09:58',
          recovery_end_time: '10:30',
          anesthetic_duration_minutes: 70,
          procedure_duration_minutes: 55
        },
        total_billed_amount: 550.0,
        billing_status: 'FATURADO',
        notes: 'Recuperação pós-anestésica tranquila, extubado após retorno dos reflexos protetores de tosse e deglutição.',
        created_at: new Date().toISOString()
      },
      {
        id: offset + 2,
        owner_id: userId,
        code: 'AN-2026-002',
        patient_id: offset + 2,
        patient_name: 'Mel',
        patient_species: 'Felina',
        patient_breed: 'SRD (Frajola)',
        patient_age: '3 anos',
        patient_weight_kg: 4.2,
        tutor_id: offset + 2,
        tutor_name: 'Carlos Eduardo Prado',
        clinic_id: offset + 2,
        clinic_name: 'Clínica Veterinária PetSoul Moema',
        surgeon_id: offset + 2,
        surgeon_name: 'Dra. Camila Toledo',
        procedure_name: 'Tartarectomia profilática e profilaxia dentária ultrassônica',
        status: 'FINALIZADA',
        asa_classification: 'ASA I',
        procedure_type: 'ELETIVA',
        date_time: `${todayStr}T13:30:00`,
        pre_anesthetic_evaluation: {
          fasting_water_hours: 2,
          fasting_food_hours: 6,
          general_condition: 'Boa condição, dócil.',
          heart_rate_bpm: 155,
          respiratory_rate_mpm: 28,
          blood_pressure: '120/75',
          body_temperature_c: 38.3,
          hydration_status: 'Normal (Adequada)'
        },
        procedure_times: {
          mpa_time: '13:40',
          induction_time: '13:55',
          anesthesia_start_time: '14:00',
          procedure_start_time: '14:10',
          procedure_end_time: '14:40',
          anesthesia_end_time: '14:45',
          extubation_time: '14:52',
          recovery_end_time: '15:20',
          anesthetic_duration_minutes: 45,
          procedure_duration_minutes: 30
        },
        total_billed_amount: 450.0,
        billing_status: 'FATURADO',
        notes: 'Tubo com cuff n° 3.5. Termorregulação preservada com colchão térmico.',
        created_at: new Date().toISOString()
      }
    ],

    documents: [
      {
        id: offset + 1,
        owner_id: userId,
        doc_type: 'RECEITUARIO',
        title: 'Receita Médica Veterinária - Thor',
        patient_id: offset + 1,
        patient_name: 'Thor',
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        content: 'Oclacitinib (Apoquel) 16mg + Shampoo Clorexidina 3% com Miconazol.',
        created_at: new Date().toISOString()
      },
      {
        id: offset + 2,
        owner_id: userId,
        doc_type: 'CARTEIRINHA',
        title: 'Carteira de Vacinação Digital - Mel',
        patient_id: offset + 2,
        patient_name: 'Mel',
        tutor_id: offset + 2,
        tutor_name: 'Carlos Eduardo Prado',
        content: 'Reforço anual de vacina V5 e antirrábica aplicado com sucesso.',
        created_at: new Date().toISOString()
      },
      {
        id: offset + 3,
        owner_id: userId,
        doc_type: 'ORCAMENTO',
        title: 'Orçamento de Atendimento Domiciliar e Procedimento - Thor',
        patient_id: offset + 1,
        patient_name: 'Thor',
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        content: 'Consulta Domiciliar (R$ 180,00) + Raspado Cutâneo (R$ 60,00). Total: R$ 240,00.',
        created_at: new Date().toISOString()
      },
      {
        id: offset + 4,
        owner_id: userId,
        doc_type: 'FICHA_ANESTESICA',
        title: 'Ficha Anestésica Oficial - Thor (AN-2026-001)',
        patient_id: offset + 1,
        patient_name: 'Thor',
        tutor_id: offset + 1,
        tutor_name: 'Mariana Silveira Ramos',
        clinic_id: offset + 1,
        clinic_name: 'Hospital Veterinário Jardins 24h',
        content: 'Procedimento cirúrgico de exérese de mastocitoma sob anestesia balanceada.',
        created_at: new Date().toISOString()
      }
    ],


  };
}

export function getFreshDatabaseData() {
  return {
    users: [
      {
        id: 1,
        email: 'ncodestechnologies@gmail.com',
        hashed_password: bcrypt.hashSync('Taijou13!', 10),
        first_name: 'Programador',
        last_name: 'NCodes Technologies',
        phone: '(11) 99999-0000',
        whatsapp: null,
        crmv: null,
        crmv_uf: null,
        clinic_name: null,
        logo_url: null,
        role: 'ADMIN',
        is_active: true,
        plan: 'PRO',
        subscription_status: 'ACTIVE',
        subscription_origin: 'AUTONOMO_CADASTRO',
        is_lifetime: true,
        subscription_start: new Date().toISOString(),
        subscription_end: null,
        admin_notes: 'Administrador e programador da plataforma NCodes Technologies',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        email_verified: true,
      },
      {
        id: 2,
        email: 'vetteste@gmail.com',
        hashed_password: bcrypt.hashSync('Nikolas13', 10),
        first_name: 'Veterinário',
        last_name: 'Teste',
        phone: '(11) 98765-4321',
        whatsapp: '(11) 98765-4321',
        crmv: '12345',
        crmv_uf: 'SP',
        clinic_name: 'Atendimento Volante & Domiciliar',
        logo_url: null,
        role: 'VET',
        is_active: true,
        plan: 'FREE',
        subscription_status: 'ACTIVE',
        subscription_origin: 'AUTONOMO_CADASTRO',
        is_lifetime: false,
        subscription_start: new Date().toISOString(),
        subscription_end: null,
        admin_notes: 'Conta de teste manual do veterinário',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        specialty_anesthesia_enabled: false,
        email_verified: true,
      },
    ],
    tutors: [],
    patients: [],
    appointments: [],
    consultations: [],
    inventory_items: [],
    financial_entries: [],
    clinics: [],
    surgeons: [],
    anesthesia_records: [],
    services: [
      { id: 1, name: 'Consulta Clínica Volante Domiciliar', category: 'CONSULTA', price: 180, description: 'Atendimento clínico geral em domicílio com anamnese, exame físico e orientação', is_active: true },
      { id: 2, name: 'Retorno Clínico Volante (até 15 dias)', category: 'CONSULTA', price: 90, description: 'Reavaliação clínica e evolução do paciente', is_active: true },
      { id: 3, name: 'Consulta de Emergência / Plantão Volante', category: 'CONSULTA', price: 260, description: 'Atendimento de urgência e emergência domiciliar', is_active: true },
      { id: 4, name: 'Aplicação de Injetável (SC / IM)', category: 'PROCEDIMENTO', price: 35, description: 'Administração de medicação injetável com assepsia', is_active: true },
      { id: 5, name: 'Curativo & Higienização Local', category: 'PROCEDIMENTO', price: 50, description: 'Limpeza, antissepsia e curativo de feridas ou pós-cirúrgico', is_active: true },
      { id: 6, name: 'Fluidoterapia Ambulatorial', category: 'PROCEDIMENTO', price: 80, description: 'Terapia de hidratação e reposição eletrolítica ambulatorial', is_active: true },
      { id: 7, name: 'Coleta de Sangue / Triagem de Amostras', category: 'EXAME', price: 45, description: 'Punção venosa, fracionamento e acondicionamento para laboratório', is_active: true },
      { id: 8, name: 'Limpeza e Tratamento Otológico', category: 'PROCEDIMENTO', price: 60, description: 'Remoção de cerúmen e instilação de solução otológica', is_active: true },
      { id: 9, name: 'Corte de Unhas & Higiene Sanitária', category: 'PROCEDIMENTO', price: 30, description: 'Corte seguro de unhas e limpeza higiênica de patas', is_active: true },
      { id: 10, name: 'Sondagem Uretral e Alívio Vesical', category: 'PROCEDIMENTO', price: 130, description: 'Desobstrução e esvaziamento vesical em cães e gatos', is_active: true },
      { id: 11, name: 'Vacina V10 / Polivalente Canina (Dose + Aplicação)', category: 'VACINA', price: 110, description: 'Imunização contra cinomose, parvovirose, hepatite, leptospirose e coronavírus', is_active: true },
      { id: 12, name: 'Vacina V8 Canina (Dose + Aplicação)', category: 'VACINA', price: 100, description: 'Imunização óctupla canina preventiva', is_active: true },
      { id: 13, name: 'Vacina V4 / V5 Felina (Dose + Aplicação)', category: 'VACINA', price: 120, description: 'Imunização contra panleucopenia, calicivirose, rinotraqueíte e clamidiose/leucemia', is_active: true },
      { id: 14, name: 'Vacina Antirrábica (Dose + Aplicação)', category: 'VACINA', price: 80, description: 'Imunização contra raiva animal', is_active: true }
    ],
    documents: [],
    audit_logs: [],
    subscriptions: []
  };
}
