"""001_initial_consolidated_schema

Revision ID: e3f879596d03
Revises: 
Create Date: 2026-09-23 08:13:02.639839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f879596d03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('crmv', sa.String(length=50), nullable=True),
    sa.Column('crmv_uf', sa.String(length=2), nullable=True),
    sa.Column('clinic_name', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('VET', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', name='subscriptionplan'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('subscription_origin', sa.String(length=100), nullable=True),
    sa.Column('is_lifetime', sa.Boolean(), nullable=False),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=150), nullable=True),
    sa.Column('target_user_name', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('MEDICAMENTO', 'PRODUTO', name='inventoryitemtype'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active_ingredient', sa.String(length=150), nullable=True),
    sa.Column('presentation', sa.String(length=100), nullable=True),
    sa.Column('concentration', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('stock_quantity', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_owner_id'), ['owner_id'], unique=False)

    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=30), nullable=True),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutors_owner_id'), ['owner_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('CANINA', 'FELINA', 'EQUINA', 'BOVINA', 'OVINA', 'CAPRINA', 'SUINA', 'LAGOMORFA', 'ROEDORES', 'AVES', 'REPTEIS', 'ANFIBIOS', 'MUSTELIDEOS', 'SILVESTRES', 'OUTRA', name='species'), nullable=False),
    sa.Column('custom_species', sa.String(length=100), nullable=True),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MACHO', 'FEMEA', 'INDEFINIDO', name='patientgender'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('approximate_age', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('coat_color', sa.String(length=100), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=False),
    sa.Column('microchip', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('appointment_type', sa.Enum('DOMICILIAR', 'CONSULTORIO', 'EMERGENCIA', 'RETORNO', 'VACINACAO', 'PROCEDIMENTO', 'OUTRO', name='appointmenttype'), nullable=False),
    sa.Column('status', sa.Enum('AGENDADO', 'CONFIRMADO', 'EM_ATENDIMENTO', 'CONCLUIDO', 'CANCELADO', name='appointmentstatus'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_date_time'), ['date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('financial_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('entry_type', sa.Enum('RECEITA', 'DESPESA', name='financialtype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.Enum('PIX', 'DINHEIRO', 'CARTAO_DEBITO', 'CARTAO_CREDITO_VISTA', 'CARTAO_CREDITO_PARCELADO', 'TRANSFERENCIA', 'BOLETO', 'OUTRO', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'CANCELADO', name='financialstatus'), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_entries_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_entries_owner_id'))
        batch_op.drop_index(batch_op.f('ix_financial_entries_id'))

    op.drop_table('financial_entries')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_date_time'))

    op.drop_table('appointments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_patients_owner_id'))
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))

    op.drop_table('patients')
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutors_owner_id'))
        batch_op.drop_index(batch_op.f('ix_tutors_name'))
        batch_op.drop_index(batch_op.f('ix_tutors_id'))

    op.drop_table('tutors')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_owner_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
